[General]
; 以管理員模式啟動: true / false
AdminMode=true

[Hotkeys]
; 可自訂切換 AltNum 模式的熱鍵, 目前預設是F8
ToggleSuspendKey=F8

[TrigKey]
;自訂觸發的按鍵
;左右邊或空白: L / R / ALL(不分左右)
Side=ALL
;按鍵: Alt / Ctrl / Shift / Win(只能是這四個)
Modifier=Alt
